### ISSUE TITLE
Separate snapshot store from event store

### ISSUE THREAD

**Issue by jesjos** [Sandthorn/sandthorn#16]
# Why?
- Right now, Sandthorn expects all event store drivers to implement an API for snapshotting. But some implementations will definitely not support this functionality, or will implement it on another level.
- Decoupling: separating them means we can, for example, use Sequel for the events, but MemCached for snapshots.
# Suggestion
- Separate drivers for `event_store` and `snapshot_store`. Snapshot stores could be defined in the same way that named event stores are defined in an upcoming pull request (I'm writing it as we speak...)

**Comment by hallgren** [comment]
After a year of thinking I think this could be a bad idea. When all aggregates of a specific type is fetched (`.all`), all ids of the aggregate type need to be collected to be able fetch all snapshots from a key-value store like MemCached. To be able to get this list we need to ask the event store, when we have the id list we need to fetch the snapshots mapped to the ids, after that we also need to fetch eventual events that occurred after the snapshot was taken. Probably not very efficient. 

The most efficient way is probably to append snapshots to the event stream with a special event_name that could be excluded on projection generations. Snapshots are an internal optimisation to speed up loading of aggregates and should probably be handled inside an event store.

**Comment by jesjos** [comment]
I agree. The way to do it is to delegate snapshotting to the event store. Sandthorn should forget everything it knows about snapshots.

**Comment by hallgren** [comment]
We need to get the snapshot data from the aggregate in some way, as the event store only know how to handle events. Do you have any idea how we could handle this without snapshot functionality in  Sandthorn?

**Comment by hallgren** [comment]
One way is to generate a snapshot as an event and store it like an event via 'aggregate.save'. This would move the responsible to the event store in a nice way I think.

In more technical words we would store every instance variable of the aggregate in the delta array and use a reserved event name to indicate that its an snapshot. I don´t see any problem with adding the aggregate_version by one for the snapshot, or? 

It would also simplify the re-building of the aggregates.

**Comment by hallgren** [comment]
After the rewrite of the api between sandthorn and its drivers the first idea is now possible and the way to go.

**Comment by hallgren** [comment]
Snaspshot support is released in version 1.2.0 https://github.com/Sandthorn/sandthorn/pull/60
