### ISSUE TITLE
Delegate `all` and `find` to event store implementation

### ISSUE THREAD

**Issue by jesjos** [Sandthorn/sandthorn#19]
Currently, when calling `Aggregate::all`, and `Aggregate::find` with many aggregates, we map `Aggregate::find` on an array of aggregate ids.

I think future event store implementations will want to decide for themselves about how to find multiple aggregates most efficiently.

I therefore propose that we make the following changes:

- Event stores must implement `get_aggregate` for a single aggregate id and multiple ids. The "arity" of the return value shall always match that of the argument, i.e. if I call it with an array of one aggregate id it returns an array of one aggregate.
- Event stores must implement `get_aggregates_by_type` with one argument - the aggregate type, which may be a string or the actual class. It returns an enumerable collection of aggregates.
- We rename `get_aggregate_list_by_typename` to `get_aggregate_ids_by_type` to reflect the actual return value.
- Sandthorn shall delegate calls to `find` and `all` to the corresponding event store method instead of juggling ids on its own.

I plan on writing this into the event store spec that will go online [here](http://github.com/Sandthorn/sandthorn_event_store_spec) shortly.

**Comment by hallgren** [comment]
I could not agree more. 

I think the event stores should expose and `.all` and `.find` interface to Sandthorn, the id juggling and the current structure is probably legacy from how the `sandthorn_driver_sequel` event store works internally. 

I don´t know if the internal method structure in a event store is of interest of defining. I mean `get_aggregate_ids_by_type` may be relevant for the `sandthorn_driver_sequel` but not for a event store based on other storage.

**Comment by hallgren** [comment]
@jesjos Do you think its ok to bump Sandthorn to `0.12.0` with this changes making it only work with  version `3.1.0` of `sandthorn_driver_sequel`?
