### ISSUE TITLE
Deleting aggregates

### ISSUE THREAD

**Issue by jesjos** [Sandthorn/sandthorn#24]
# In general

Deleting aggregates is a nice feature to have. There should always be a way of undoing mistakes, like creating an unwanted aggregate. Right now, if I mistakenly create a crazy aggregate, it is up to me to implement logic for removing the aggregate. I think we could at least in theory handle this in the library as an optimization for a very common use case.

It is easy enough to create standard commands and events that mark the aggregate as deleted. The question is how to handle the effects of this. I will try to enumerate some potential issues.
# Potential Issues
## Finding aggregates

I guess `::find` and `::all` should be expected to return only non-deleted aggregates. I recommend that `find!` throws an `AggregateDeleted` error if you try to find a deleted aggregate. `all` should just skip all deleted aggregates. They should both have an option for returning aggregates that are deleted.

Problems may arise if there are apps in the wild that already implement similar features on the application level. 
## Getting events

I think the basic premise when getting events should be that the client always gets all events, including those that belong to a deleted aggregate. The effect of this is that all consumers that want to keep an aggregate state of their own must always keep track of deleted aggregates. It would've been nice to elect to not receive events from deleted aggregates, but I suspect that this would be complicated for some event stores to implement. If we choose to support building aggregates to a certain sequence number (instead of always to the most recent state) would compound this complexity.

**Comment by hallgren** [comment]
Ruby 2.0 does not support the default keyword argument, that forces the deleted: keyword to always be supplied in the find method.

https://robots.thoughtbot.com/ruby-2-keyword-arguments
