### ISSUE TITLE
Rewrite AggregateRoot#commit

### ISSUE THREAD

**Issue by jesjos** [Sandthorn/sandthorn#28]
Commit should create well-formed events. 
Also, it looks like commit doesn't create events if there are no attribute deltas. Is this really the desired behavior? Wouldn't you want to be able to create an event that changes no attributes?

**Comment by hallgren** [comment]
I just bumped into the issue that I could not create an event if no attribute were changed. I think its up to the creator to decide if the event hold state changed or not.

**Comment by jesjos** [comment]
:+1:
