### ISSUE TITLE
Mapping aggregates to event stores

### ISSUE THREAD

**Issue by jesjos** [Sandthorn/sandthorn#30]
@hallgren and I discussed how to map aggregates to event stores. I used to think that the aggregates themselves should declare were they belong. @hallgren thinks it belongs in a centralized map of some sort, in the Sandthorn config. I think he's probably right. We should add this feature, and remove the event_store config from AggregateRoot.

**Comment by jesjos** [comment]
The EventStores class could perhaps perform this job.

**Comment by hallgren** [comment]
@jesjos This is dealt with in the latest release 0.9.1, can I close this?
