### ISSUE TITLE
Delegate several methods in AggregateRoot to the relevant event store

### ISSUE THREAD

**Issue by jesjos** [Sandthorn/sandthorn#31]
Currently, AggregateRoot performs a lot of work, like building aggregates by fetching events and snapshots. This functionality should be delegated to the event store.
Affected methods:

- aggregate_find
- aggregate_build

There may be other affected methods.

**Comment by hallgren** [comment]
After the discussion in issue #16 I think this issue could be closed if I understands it correctly. ping @jesjos
