### ISSUE TITLE
some brain exhaustion 

### ISSUE THREAD

**Issue by hallgren** [Sandthorn/sandthorn#32]
This is only something that my brain made up after some whiskey. Can be totally wrong but here it comes.
1. The main Sandthorn gem should probably only handle the setup part of the stores (where the data of the aggregates are stored) and know nothing about how the data of the aggregates are stored or what the save or commit method are and the format of the data should be up to the stores to decide.
2. The stores can be an EventStore or a CRUDStore for example and its up to them internally how they decide to arrange the data that will result in an aggregate. The API between Sandthorn and a store should be an aggregate (an object).
3. A store can decide on how it wants to implement its storage. For example the EventStore could inject a SequelDriver to store the events in a sql database or an InMemoryDriver to store the events in memory. It could also inject a SnapshotDriver to speed up the read of an aggregate. 
   The CRUDStore could use ActiveRecord as a driver to store the data for example.

---

Projections

A projection should include an EventStore instead of Sandthorn. I haven´t looked on how the event filter works so don´t know if this is a good or bad idea..

**Comment by hallgren** [comment]
A Driver for the EventStore should probably implement:
   
* save_events
* find_events

And the EventStore should implement:

* find_aggregate
* find_all_aggregates
* Its up to the event store on how the event format should look.
* Aggregate root should be implemented here with the commit and save methods.

**Comment by jesjos** [comment]
I don't agree with you on some points:

1. The aggregate root class should live in Sandthorn. When you build your aggregates, you should not be tied to a particular event store.

2. I don't see what you mean by having the aggregate be the API, but it sounds like you're giving the aggregate too much responsibility.

3. Sure

Regarding having an abstract event store class that you inject drivers into, I think this is an unneeded complication. I think it makes more sense to have classes like SequelStore and CRUDStore that already know everything they need to know. You could inject SnapshotStores into them if needed. Any shared logic could be placed in a module or a superclass that we call EventStore, but frankly I think it would be nicer if they share nothing except for the fact that they pass all the tests in some shared test suite for event stores.

**Comment by jesjos** [comment]
I think EventStore could decide its internal event format, but it's really important that events that travel in and out of the EventStore comply with a common event format.

**Comment by jesjos** [comment]
Okay I partly see your point with having EventStore-customized aggregate root classes. For example, if using an over-the-wire store, commands would be executed immediately on commit and save would have no particular function. 

May I suggest that we still provide a common AggregateRoot class, either in Sandthorn or in some other shared package. Most implementations that build upon some kind of SQL-ish datastore will be able to use a common implementation.

**Comment by jesjos** [comment]
Oh and I think a projection should be given an event store, rather than including it. Like this:

    # definition

    class MyProjection < Sandthorn::Projection
    end

    # Projection config

    projections_to_run = [] << MyProjection.new(some_event_store)

**Comment by jesjos** [comment]
To make our discussions more concrete, here's some code:

https://gist.github.com/jesjos/3072f9b95f003d68ab39

Feel free to fork and make changes.
