### ISSUE TITLE
A DSL for committing

### ISSUE THREAD

**Issue by jesjos** [Sandthorn/sandthorn#33]
Presently, when committing an event we use some magic to make the name of the calling method the name of the event. This doesn't feel very safe, nor very clean. 

I propose that we introduce a DSL for defining events.

A class method `events` could be used to declare events. It defines instance methods for each event. The instance methods would create an event with the correct name. They also accept an optional hash of meta data. This way, you don't have to explicitly create methods just to create an event with the desired name. 

It could look like this in use:

    module AggregateRoot

      def self.included(base)
        base.extend(ClassMethods)
      end
      
      module ClassMethods
        def events(*event_names)
          event_names.each do |name|
            def_method(name) do |meta|
              create_event(name: name, meta: meta)
            end
          end
        end
      end

      def create_event(name:, meta: {})
        # creates a valid event
      end
    end

    class MyAggregate
      include Sandthorn::AggregateRoot

      events :name_changed, :some_other_event, :third_event

      def change_name(name)
        if @name != name
          @name = name
          name_changed
        end
      end
    end

    aggregate = MyAggregate.new
    aggregate.change_name("foo")
    aggregate.save

**Comment by hallgren** [comment]
Removed the 2.0 label because this can be merged and is not be a breaking change.

**Comment by hallgren** [comment]
@jesjos is it ok to merge and close?
